
baseURL = "https://denm.ch"
languageCode = "en-us"
title = "Den McHenry"
theme = "ananke"
publishdir = "denmch.github.io"

[params]
    subtitle = "Web Developer"
    featured_image = "/images/apoc-header-bw.jpg"
    description = "Web Developer. Cartoonist. Dad of the Year."
    header_style = "background-position: center;"
    logo = "/images/rookish-crow.png"
    twitter = "https://twitter.com/denmch"
    github = "https://github.com/denmch"
    codepen = "https://codepen.io/denmch"
    linkedin = "https://www.linkedin.com/in/denmch/"
    stackoverflow = "https://stackoverflow.com/users/2953245/denmch?tab=profile"
    medium = "https://medium.com/@denmch"
    spotify = "https://open.spotify.com/user/dmmchenry"
    dribbble = "https://dribbble.com/denmch"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

  [menu]
    [[menu.main]]
    identifier = "Résumé"
    name       = "Résumé"
    url        = "/resume/"
    weight     = 0

    [[menu.main]]
    identifier = "About Den"
    name       = "About Den"
    url        = "/about-den/"
    weight     = 0